# to execute 
# ansible-playbook -i inventory/inventory_file backup.yaml -e "file_suffix=test"-t create,[remote|local] --skip-tags debug
# ansible-playbook -i inventory/inventory_file backup.yaml -e "file_suffix=test"-t delete,[remote|local] --skip-tags debug
# ansible-playbook -i inventory/inventory_file backup.yaml -e "file_suffix=test"-t apply,[remote|local]  --skip-tags debug

# ansible-playbook -i inventory/inventory_file backup.yaml -e "file_suffix=test123"  -t apply[local|remote] --skip-tags debug
#ansible-playbook -i inventory/<inventory_file>.yml backup.yaml -e "file_suffix=test123" -t apply,remote


- hosts: devices
  gather_facts: no

  tasks:
  #  - debug: 
  #      msg: "{{hostvars[inventory_hostname]}}"
  #    tags: debug
      
    - name: Set 8x OS variables
      set_fact:
        ansible_network_os: "saos8x" 
        saos_os: "8x"
        ansible_connection: "network_cli"
      when: "'devices_8x' in hostvars[inventory_hostname]['group_names']"
      tags: always

    - name: Set 6x OS variables
      set_fact:
        ansible_network_os: "saos6x" 
        saos_os: "6x"
        ansible_connection: "network_cli"
      when: "'devices_6x' in hostvars[inventory_hostname]['group_names']"
      tags: always

    - name: Set 10x OS variables
      set_fact:
        ansible_network_os: "saos10x" 
        saos_os: "10x"
        ansible_connection: "netconf"
      when: "'devices_10x' in hostvars[inventory_hostname]['group_names']"
      tags: always      

    - name: Set create action variables    
      set_fact:
        crud: create
      tags: create

    - name: Set apply action variables    
      set_fact:
        crud: apply
      tags: apply

    - name: Set delete action variables    
      set_fact:
        crud: delete
      tags: delete

    - import_role:
        name: backup

#- import_playbook: backup_10x.yaml
#  when: ansible_network_os == "saos10x" 
#- import_playbook: backup_6x.yaml
#  when: ansible_network_os == "saos6x" 
#- import_playbook: backup_8x.yaml
#  when: ansible_network_os == "saos8x" 