---
# to execute 
# ansible-playbook -i inventory/inventory_file banner_10x.yaml -t create --skip-tags debug
# ansible-playbook -i inventory/inventory_file banner_10x.yaml -t delete --skip-tags debug
# ansible-playbook -i inventory/inventory_file banner_10x.yaml -t get  --skip-tags debug

- hosts: devices_6x
  gather_facts: no
  connection: network_cli
  vars: 
    saos_os: "6x"
    ansible_network_os: "saos6x"    

  tasks:
    - set_fact: 
        crud: create
      tags: create
    - set_fact: 
        crud: get
      tags: get      
    - set_fact: 
        crud: delete
      tags: delete   
    - import_role:
        name: banner

