---
# to execute 
# ansible-playbook -i inventory/inventory_file banner_10x.yaml -e "crud=create" --skip-tags debug
# ansible-playbook -i inventory/inventory_file banner_10x.yaml -e "crud=delete" --skip-tags debug
# ansible-playbook -i inventory/inventory_file banner_10x.yaml -e "crud=get"  --skip-tags debug

- hosts: devices_6x
  gather_facts: no
  connection: network_cli
  vars: 
    saos_os: "6x"
    ansible_network_os: "saos6x"    

  tasks:
    - import_role:
        name: banner

