---
# to execute 
# ansible-playbook -i inventory/inventory_file banner_10x.yaml -e "crud=create" --skip-tags debug
# ansible-playbook -i inventory/inventory_file banner_10x.yaml -e "crud=delete" --skip-tags debug
# ansible-playbook -i inventory/inventory_file banner_10x.yaml -e "crud=get"  --skip-tags debug

- hosts: devices_8x
  gather_facts: no
  connection: network_cli
  vars: 
    saos_os: "8x"
    ansible_network_os: "saos8x"    

  tasks:
    - set_fact: 
        crud: create
      tags: create
    - set_fact: 
        crud: get
      tags: get      
    - set_fact: 
        crud: delete
      tags: delete 
      
    - import_role:
        name: banner

