---
- name: "TASK: {{crud}} banner"
  netconf_config:
    content: "{{ lookup('template', './banner_{{ saos_os }}_{{crud}}.j2') }}"
    target: running
    #backup: yes
    format: xml
    lock: if-supported
    default_operation: merge
    error_option: rollback-on-error
  register: nc_result
  when: ansible_network_os == "saos10x" and (crud == 'create' or crud == 'delete')

- name: "TASK: Print output"
  tags:
     - debug
  debug:
    msg: "{{ nc_result }}"
  when: ansible_network_os == "saos10x" and (crud == 'create' or crud == 'delete')