---
- name: "TASK: {{crud}} banner"
  netconf_config:
    content: "{{ lookup('template', './banner_{{ saos_os }}_{{crud}}.j2') }}"
    target: running
    #backup: yes
    format: xml
    lock: if-supported
    default_operation: merge
    error_option: rollback-on-error
  register: nc_result
  when: ansible_network_os == "saos10x" and (crud == 'create' or crud == 'delete')
  tags: 
    - create
    - delete

- name: "TASK: Print output"
  tags:
    - debug
    - create
    - delete
  debug:
    msg: "{{ nc_result }}"
  when: ansible_network_os == "saos10x" and (crud == 'create' or crud == 'delete')

- name: "TASK:Get banner"
  netconf_rpc:
    display: json
    rpc: get
    content: "{{ lookup('template', './banner_{{saos_os}}_{{crud}}.j2') }}"
  register: nc_result
  when: ansible_network_os == "saos10x" and crud == "get"
  tags: get
  
- name: "TASK: Print output"
  tags:
    - debug
    - get
  debug:
    msg: "{{ nc_result.stdout_lines }}"
  when: ansible_network_os == "saos10x" and crud == "get"