---
- name: "TASK: {{crud}} VS via CLI"
  cli_command:
    command: "{{ lookup('template', './ipv4_iface_{{ saos_os }}_vs_{{crud}}.j2') }}"
  register: cli_result
  when: ansible_network_os == "saos8x" and (crud == 'create' or crud == 'delete')
  run_once: true
  ignore_errors: yes
  tags: 
    - create
    - delete